### ISSUE TITLE
The custom themed indicator keeps reverting to default theme

### ISSUE THREAD

**Issue by Aleksandra0056** [schilkyl/incognito-indicator#5]
The custom themed indicator (Opera, Chrome, Safari, Edge) keeps reverting to default theme (Firefox) after restarting the browser.

**Comment by SeaNettleStudios** [comment]
Turns out the `onCreated` event isn't enough to handle when the first instance of the browser starts. Unfortunately, neither is [`onStartup`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/runtime/onStartup) since it won't run for incognito. On top of all that, I wasn't testing the extension thoroughly enough or in a dev browser so the theme reset slipped by me.

All that said, this should be addressed in release [2.0.1](https://github.com/sea-nettle-studios/private-indicator/releases/tag/2.0.1)
